#!/usr/bin/env php
<?php
require dirname(dirname(__DIR__)) . '/jitsu/error/error.php';
require dirname(dirname(__DIR__)) . '/autoload.php';
require dirname(__DIR__) . '/bin-src/jitsu-config-template.php';
